spring:
  application:
    name: TripMate
  profiles:
    include: oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripmatedb
    username: ssafy
    password: ssafy

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      com.ssafy: DEBUG

  mybatis:
    type-aliases-package: com.ssafy.tripmate.*.dto
    mapper-locations: mapper/*.xml